#!/bin/bash

Bamlocation=$1
LeafcutterLoc=$2
PATH=$PATH:$LeafcutterLoc/scripts

if [ -e juncfiles.txt ]
then 
	rm juncfiles
fi 
for bamfile in "ls $Bamlocation/*.bam"
do 
	echo Converting $bamfile to $bamfile.junc
	sh $LeafcutterLoc/scripts/bam2junc.sh $bamfile $bamfil.junc
	echo $bamfile.junc >> juncfiles.txt
done

python $LeafcutterLoc/clustering/leafcutter_cluster.py -j juncfiles.txt -m 50 -o testYRIvsEU -l 500000

if [ -e test_diff_intron.txt ]
then
	rm test_diff_intron.txt
fi

for lib in `cut -f 3 -d'/' $Bamlocation/juncfiles.txt | cut -f 1-4 -d'.' | grep YRI`
do
	echo $lib YRI >> diff_intron.txt
done

for lib in `cut -f 3 -d'/' $Bamlocation/juncfiles.txt | cut -f 1-4 -d'.' | grep CEU`
do
	echo $lib CEU >> diff_intron.txt
done

$LeafcutterLoc/scripts/leafcutter_ds.R --num_threads 4 $Bamlocation/testYRIvsEU_perind_numers.counts.gz $Bamlocation/diff_intron.txt

